### ISSUE TITLE
Fix thus error

### ISSUE THREAD

**Issue by Astro-PM** [refteams/libNpcDialogue#10] opened 2023-04-25 06:19 UTC
pocketmine\network\mcpe\protocol\AddActorPacket::create(): Argument #9 ($bodyYaw) must be of type float, array given, called in phar://C:/Users/******/Desktop/FAIL SERVER/test/virions/libNpcDialogue_dev-2.phar/src/ref/libNpcDialogue/NpcDialogue.php on line 105" (EXCEPTION) in "pmsrc/vendor/pocketmine/bedrock-protocol/src/AddActorPacket" at line 56

**Comment by alvin0319** [comment] 2023-04-25 06:45
Duplicate of #8, I will take a look at this soon.

**Closed as not planned by alvin0319** 2023-04-25 06:45 UTC
